// <auto-generated />
namespace Nsu.Belov.TrainsDatabase.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fluentapi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fluentapi));
        
        string IMigrationMetadata.Id
        {
            get { return "201805151506196_fluent api"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
